Feature/#laravel responder
ThuyDuong-Nami/02_blog_laravel pull request #9
Opened 2021-04-07 04:31 UTC by ThuyDuong-Nami

2021-04-07 04:59 UTC, nguyenhuutuananh requested changes
Xem dùm anh mấy cái comment với anh thấy không sử dụng UserTransformer sau khi login hay gọi api /me

2021-04-07 04:59 UTC, nguyenhuutuananh commented on app/Http/Controllers/API/PostResourceController.php
> +//        return response()->json($posts, 200);
Xóa comment nha em

2021-04-07 04:59 UTC, nguyenhuutuananh commented on app/Transformers/PostTransformer.php
> +    protected $relations = [];
Dùng relation trong model thay vì ```user' => transformation($post->user)->transform(),``` trong attribute

2021-04-07 04:59 UTC, nguyenhuutuananh commented on app/Models/User.php
> +    }
gọi hàm này dùng để làm gì vậy em?

2021-04-07 07:04 UTC, ThuyDuong-Nami commented on app/Models/User.php
> +    }
dạ này là em "implements Transformable" nó tự sinh ra em nghĩ là dùng để nối từ model tới transformer để có thể sử dụng định dạng theo ý mình bên transformer ạ

2021-04-08 08:29 UTC, nguyenhuutuananh approved these changes

2021-04-08 08:29 UTC, merged